In [1]:
import numpy as np

In [9]:
################## create ndarray from pre-maid list
first_arr = np.array([1, 2, 3])
print(first_arr)
type(first_arr) # [[1,2,3], [4,5,6]]

[1 2 3]


numpy.ndarray

In [5]:
np.array((1,2,3))

array([1, 2, 3])

In [26]:
matrix = [[1,2,3], [4,5,6], [7,8,9]]
np.array(matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [39]:
################## create ndarray from range
for x in range(0, 10, 1):
    print(x, end = '   ')
print()    
print(*np.arange(0, 10, 1)) # print * = numbers only
print(*np.arange(10))       # print * = numbers only
# create nparray from numerbs 7, 14, 21 ... to 105 [include]
print(np.arange(7, 105 + 1, 7))
np.arange(7, 105 + 1, 7)[4]

0   1   2   3   4   5   6   7   8   9   
0 1 2 3 4 5 6 7 8 9
0 1 2 3 4 5 6 7 8 9
[  7  14  21  28  35  42  49  56  63  70  77  84  91  98 105]


35

In [43]:
################## create ndarray from zeros
print(np.zeros(5, dtype=float))
print(np.zeros(5, dtype=int))
print(np.zeros((3, 5), dtype=int))
print(*np.zeros((3, 5), dtype=int))

[0. 0. 0. 0. 0.]
[0 0 0 0 0]
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]
[0 0 0 0 0] [0 0 0 0 0] [0 0 0 0 0]


In [47]:
################## create ndarray from range split
lin_array = np.linspace(0, 10, 5, dtype=np.float64)
# 0 2.5 5 7.5 10 
lin_array = np.linspace(0, 12, 7, dtype=int)
# 0 2 4 6 8 10 12
lin_array

array([ 0,  2,  5,  7, 10])

In [59]:
################## create ndarray from random numbers
print(np.random.random(4))  # between 0-1
print(np.random.rand(4, 4)) # between 0-1
print(np.random.randint(0, 10 + 1, (3, 3))) # between 0-10
np.random.uniform(10, 100, size=5)

[0.66976202 0.37896769 0.02100318 0.56251728]
[[0.29661505 0.66603955 0.61943068 0.07244229]
 [0.22282787 0.96631968 0.86804865 0.13283787]
 [0.90400515 0.00317159 0.12335437 0.42050787]
 [0.39916951 0.26446498 0.120009   0.29345336]]
[[9 9 6]
 [9 4 6]
 [7 0 9]]


array([93.88164054, 26.57281248, 14.48981079, 49.06658675, 68.52606412])

In [60]:
np.array([True, False])

array([ True, False])

In [85]:
np.random.seed(42)
print(np.random.randint(0, 100, (2, 5)))

[[51 92 14 71 60]
 [20 82 86 74 74]]


In [95]:
arr = np.random.randint(0, 100, size=(2, 5))
print(arr)
arr.reshape(1, 10)

[[25 88 59 40 28]
 [14 44 64 88 70]]


array([[25, 88, 59, 40, 28, 14, 44, 64, 88, 70]])

In [115]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr)
print('max', arr.max())
print('min', arr.min())
print('arg_max index-max #', arr.argmax())
print('arg_min index-min #', arr.argmin())
print(arr.shape)

[51 92 14 71 60 20 82 86 74 74]
max 92
min 14
arg_max index-max # 1
arg_min index-min # 2
(10,)


In [120]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr)
print(arr[3])
print(arr[3:5])
print(arr[::-1])

[51 92 14 71 60 20 82 86 74 74]
71
[71 60]
[74 74 86 82 20 60 71 14 92 51]


In [135]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
print()
print(arr[0], 'arr[0]')
print(arr[1], 'arr[0]')
print(arr[0][-1], '              arr[0][-1]')
print(arr[2][3], '               arr[2][3]')
print(arr[2, 3], '               arr[2][3]')
print(arr[:, 0], 'arr[:][0]')

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]

[51 92 14 71 60] arr[0]
[20 82 86 74 74] arr[0]
60               arr[0][-1]
2                arr[2][3]
2                arr[2][3]
[51 20 87 52  1] arr[:][0]


In [142]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
arr2 = arr  # alias, shallow copy 
arr2[0] = [1, 2, 3, 4, 5]
print('arr2 \n', arr2)
print('arr \n', arr)  # also CHANGED !! -- same as deep copy
x = 5 # 5
y = x 
y = y + 1 # 6
# next cell

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr2 
 [[ 1  2  3  4  5]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr 
 [[ 1  2  3  4  5]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]


In [170]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
arr2 = arr.copy()  # deep copy
arr2[0] = [1, 2, 3, 4, 5]
print('arr2 \n', arr2)
print('arr \n', arr)  # not CHANGED !! -- same as deep copy

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr2 
 [[ 1  2  3  4  5]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
arr 
 [[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]


In [171]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5))
print(arr)
print([True, False, False, True, False])
result_55 = arr[ [True, False, False, True, False] ]  # keeps only elements with True
print(result_55)

[51 92 14 71 60]
[True, False, False, True, False]
[51 71]


In [167]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5))
print(arr)
print('arr > 55 \n', arr > 55)  # condition -> creates bool array
print()
print('arr[arr > 55]', arr[arr > 55])

[51 92 14 71 60]
arr > 55 
 [False  True False  True  True]

arr[arr > 55] [92 71 60]


In [ ]:
# 1 create 20 numbers between 0-100 (seed 42) and keep only even numbers
# 2 create 20 numbers between 0-100 (seed 42) and keep only number smllaer than 40
# 3 arr = np.array([10, 20, 30, 99, 40, 50, 99, 60]) keep only numbers not 99


In [177]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr)
print('arr > 55 \n', (arr >= 51) & (arr <= 71) )  # condition -> between 51 and 71
print()
print('arr[71 >= arr >= 55]', arr[(arr >= 51) & (arr <= 71) ])
print('arr[71 < arr or arr < 55]', arr[(arr < 55) | (arr > 71) ])

[51 92 14 71 60 20 82 86 74 74]
arr > 55 
 [ True False False  True  True False False False False False]

arr[71 >= arr >= 55] [51 71 60]
arr[71 < arr or arr < 55] [51 92 14 20 82 86 74 74]


In [182]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(10))
print(arr, 'arr')
print("+5")
print(arr + 5, 'arr + 5')

[51 92 14 71 60 20 82 86 74 74] arr
+5
[56 97 19 76 65 25 87 91 79 79] arr + 5


In [185]:
np.random.seed(42)
arr1 = np.random.randint(0, 100, size=(10))
np.random.seed(49)
arr2 = np.random.randint(0, 100, size=(10))
print(arr1, 'arr1')
print("+")
print(arr2, 'arr2')
print("=")
print(arr1 + arr2)

[51 92 14 71 60 20 82 86 74 74] arr1
+
[42 45 40 54 12 69  5 49 18 36] arr2
=
[ 93 137  54 125  72  89  87 135  92 110]


In [191]:
np.random.seed(42)
x = np.random.randint(0, 100, size=(4))
print('x')
print(x)
y = 2 * x + 3
print('y = 2 * x + 3')
print(y)

x
[51 92 14 71]
y = 2 * x + 3
[105 187  31 145]


In [202]:
np.random.seed(42)
arr = np.random.randint(0, 100, size=(5, 5))
print(arr)
print('max in matrix', arr.max())
print('max per column', arr.max(axis=0))
print('max per row', arr.max(axis=1))
print('min', arr.min())
print('arg_max index-max per column #', arr.argmax(axis=0))
print('arg_min index-min per column #', arr.argmin(axis=0))
print('sum per column', arr.sum(axis=0))
print('sum per row', arr.sum(axis=1))
print(arr.shape)

[[51 92 14 71 60]
 [20 82 86 74 74]
 [87 99 23  2 21]
 [52  1 87 29 37]
 [ 1 63 59 20 32]]
max in matrix 99
max per column [87 99 87 74 74]
max per row [92 86 99 87 63]
min 1
arg_max index-max per column # [2 2 3 1 1]
arg_min index-min per column # [4 3 0 2 2]
sum per column [211 337 269 196 224]
sum per row [288 336 232 206 175]
(5, 5)
